databases:
  - name: recipe
    databaseName: recipe_901x
    user: recipe_901x_user

services:
  - type: web
    name: recipeRails
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipe_901x
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false